routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\MinistryController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\SuperVisionController;
use App\Http\Controllers\DemandController;
use App\Http\Controllers\SvController;
use App\Http\Controllers\BudgetController;
use App\Http\Controllers\EquipmentTypeController;
use App\Http\Controllers\ProposalTypeController;
use App\Http\Controllers\ProposalController;
use App\Http\Controllers\MainCategoryController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\ItemInfoController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RecommendController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function() {
    return redirect()->route('equipment-type.index');
});

Route::get('/tem',function() {
    return view('layouts.template');
});


Route::post('/ajax-demand-store',[DemandController::class,'store'])->name('ajax-demand-store');


Route::prefix("admin")->group(function () {
    Route::resource('/ministry', MinistryController::class)->except('show');
    Route::resource('/department', DepartmentController::class)->except('show');
});

Route::prefix("supervision")->group(function () {

    Route::get('index',[SuperVisionController::class,'index'])->name('supervision.index');
    Route::get('sa-1001',[SuperVisionController::class,'exportSaone'])->name('supervision.saone');
    Route::post('importexcel', [SuperVisionController::class, 'importExcel'])->name('excel.import');
    Route::post('demandItem-excel-store', [SuperVisionController::class, 'demandStoreWithExcel'])->name('demand-excel.store');
    Route::post('demandItem-excel-export',[SuperVisionController::class,'demandItemExcelExport'])->name('demand-excel.export');
    Route::get('demandItem-excel-download',[SuperVisionController::class,'downloadExcelAllQtyVsDeps'])->name('download.excel');
    Route::get('demandItem-excel-download',[SuperVisionController::class,'downloadExcelAllQtyVsDeps'])->name('download.excel');

    Route::get('demandItem-excel-sa-one-download',[SuperVisionController::class,'downloadExcel'])->name('download.sa-one.excel');

});


Route::prefix("sv")->group(function () {

     Route::get('/',[SuperVisionController::class,'index'])->name('sv.index');
     
     Route::post('/sv-upload',[SuperVisionController::class,'importExcel'])->name('sv.upload');

     Route::post('/store/data',[SvController::class,'storeData'])->name('sv.store');
    // Route::post('importexcel', [SuperVisionController::class, 'importExcel'])->name('excel.import');
    // Route::post('demandItem-excel-store', [SuperVisionController::class, 'demandStoreWithExcel'])->name('demand-excel.store');
    // Route::post('demandItem-excel-export',[SuperVisionController::class,'demandItemExcelExport'])->name('demand-excel.export');
    // Route::get('demandItem-excel-download',[SuperVisionController::class,'downloadExcel'])->name('download.excel');

});

Route::prefix("manual")->group(function () {

    Route::get('/', [DemandController::class,'create'])->name('manual.create');
    Route::get('re/excel-import-form', [RecommendController::class,'excelImportForm'])->name('manual.re.excel-import-form');
    Route::post('re/recommend-import-form',[RecommendController::class,'recommendImport'])->name('manual.re.excel-create-store');

});
Route::resource('budget',BudgetController::class);


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix("setup")->group(function () {

Route::resource('equipment-type',EquipmentTypeController::class); 
Route::resource('main-category',MainCategoryController::class); 
Route::resource('sub-category',SubCategoryController::class); 
Route::resource('proposal-type',ProposalTypeController::class);
Route::resource('item_info',ItemInfoController::class);
Route::resource('main-proposal',ProposalController::class,['names' => 'main-proposal'])   ;

});

Route::prefix('/ajax')->group(function () {

    Route::post('/equip-type', [EquipmentTypeController::class,'getEquipmentTypes'])->name('ajax.equip_type');
    Route::post('/main_category', [MainCategoryController::class,'getMainCategories'])->name('ajax.main_category');
    Route::post('/sub_category', [SubCategoryController::class,'getSubCategories'])->name('ajax.sub_category');
    Route::post('/item_infos', [ItemInfoController::class,'getItemInfos'])->name('ajax.item_infos');
    Route::post('/propo-type', [ProposalTypeController::class,'getProposalTypes'])->name('ajax.propo_type');
    Route::post('/propo', [ProposalController::class,'getProposals'])->name('ajax.proposel');
    Route::post('/depsByMinId', [DepartmentController::class,'depsByMinId'])->name('ajax.deps_by_minid');
    Route::post('/inTransByBudgetDep', [DemandController::class,'filterWithBudgetDep'])->name('ajax.intrans_by_budget_dep');

    Route::post('/categoriesByminUUid', [MainCategoryController::class,'categoriesByMinUuid'])->name('ajax.categories_by_min_uuid');
    
});

Route::prefix("report")->group(function () {

    Route::get('/filter/budget-dep',[ReportController::class,'reportsByBYandDep'])->name('report.filter.budget_dep');

    Route::post('/filter/budget-dep/collection',[ReportController::class,'collectionByBYandDep'])->name('report.filter.budget_dep.collection');

    Route::get('/qties_with_all_deps', [SuperVisionController::class,'reportTotalWithQty'])->name('report.qties_with_all_deps');

    Route::get('/report/deps/by_minid/create',[RecommendController::class,'depRecordsByMiniCreate'])->name('report.deps_by_minid.create');

    Route::post('/report/deps/by_minid/preview',[ReportController::class,'depRecordsByMiniPreview'])->name('report.deps_by_minid.preview');

});

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\CategoryService;

class SubCategoryController extends Controller
{
    protected $service;
    public function __construct(CategoryService $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        return view('sub_category.index');
    }

    public function getSubCategories(Request $request)
    {
        return response()->json($this->service->makeItemSubCatDtCollection($request));
    }

    public function create()
    {
        $categories = $this->service->getAllItemCats();
        
        return view('sub_category.create')->with(['categories' => $categories]);
    }


    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'item_category_id' => 'required',
        ]);

        $inputs = $request->all();
        $response = $this->service->createSubCat($inputs);

        if ($response) {
            return redirect()->route('sub-category.index')
                ->with('message', 'Successfully Added!');
        } else {
            return redirect()->back()->withInput()
        ->with('error_msg', 'something went wrong!');
        }
    }


    public function edit($id)
    {
        $categories = $this->service->getAllItemCats();
        $row = $this->service->getItemSubCategoryByUuid($id);
        return view('sub_category.edit')->with(['row' => $row,'categories' => $categories]);
    }


    public function update(Request $request, $uuid)
    {
        $validated = $request->validate([
            'name' => 'required',
            'item_category_id' => 'required',
        ]);

        $inputs = $request->only('name','item_category_id');

        $row = $this->service->getItemSubCategoryByUuid($uuid);
        $response =  $this->service->subCategoryUpdate($inputs, $row->id);

        if ($response) {
            return redirect()->route('sub-category.index')
                ->with('message', 'Successfully Updated!');
        } else {
            return back()->with('error_msg', 'something went wrong!');
        }
    }




}

resources/views/sub_category/create.blade.php
@extends('layouts.frontEnd')
@section('content')

    <!-- START PAGE CONTENT-->
    
    <div class="page-heading mt-5">
        <h1 class="page-title">{{ __('key.createSubCategory') }}</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html"><i class="la la-home font-20"></i></a>
            </li>
        </ol>
    </div>
    <div class="page-content fade-in-up">
        <div class="ibox ">
            <div class="ibox-head">
                <div class="ibox-title">{{ __('key.newSubCategory') }}</div>
                <div class="ibox-tools">
                    <a class="ibox-collapse"><i class="ti-angle-down"></i></a>
                </div>
            </div>
            <div class="ibox-body card">
                <form class="form-horizontal" action="{{route('sub-category.store')}}" method="POST">
                    @csrf
                    <div class="p-4">
                        <div class="form-group mb-4 row">
                            <label for="name" class="col-2">{{__('key.name')}}</label>
                            <input class="col-8 form-control" type="text" name="name" placeholder="Name" id="name">
                            @error('name')
                            <div class="col-4"> <span class="text-danger ">{{ $message }}</span></div>
                            @enderror
                        </div>

                        <input type="hidden" name="item_category_id" id="item_category_id"  >
                            <div class="form-group mb-4 row">

                                <label  class="col-2">{{ __('key.maincategory') }}</label>
                                <select name="item_category_id" id="proposalType_selection" class="col-8 select2-show-search select2 form-control">
                                    <option selected disabled>Please Choose </option>
                                   @foreach ($categories as $category)
                                   <option value="{{ $category->id }}">{{$category->name}}</option>
                                   @endforeach
                                </select>
                                @error('item_category_id')
                                <div class="col-4"> <span class="text-danger ">{{ $message }}</span></div>
                               @enderror

                            </div>

                        <div class="form-group mb-4 float-right">
                            <button class="btn btn-success" type="submit" >{{ __('key.save') }}</button>
                            <a class="btn btn-danger"  href="{{ route('sub-category.index') }}">{{ __('key.cancel') }}</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <div>
@endsection
@section('script')
   <script>
    $(document).ready(function(){

        // $('.select2-show-search').select2({
        //     minimumResultsForSearch: '',
        //     width: '66.7%',
        //     placeholder:"Please select one",
        // });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });


        $("#proposalType_selection").on('select2:select', function (e) {

            let {value,name} = e.target;

            console.log(value);
            $('input[name="proposal_type_id"]').val(value);

        });

    })
</script>
   @endsection

resources/views/sub_category/edit.blade.php
@extends('layouts.frontEnd')
@section('content')

    <!-- START PAGE CONTENT-->
    <div class="page-heading mt-5">
        <h1 class="page-title">{{ __('key.editSubCategory') }}</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="index.html"><i class="la la-home font-20"></i></a>
            </li>
        </ol>
    </div>
    <div class="page-content fade-in-up">

        <div class="ibox ">
            <div class="ibox-head">
                <div class="ibox-title">{{ __('key.updateSubCategory') }}</div>
                <div class="ibox-tools">
                    <a class="ibox-collapse"><i class="ti-angle-down"></i></a>
                </div>
            </div>
            <div class="ibox-body card">
                <form class="form-horizontal" action="{{route('sub-category.update',$row->uuid)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="p-4">

                    
                        <div class="form-group mb-4 row">
                            <label class="col-2">{{__('key.name')}}</label>
                            <input class="col-8 form-control" type="text" name="name" value="{{$row->name ?? old('name')}}" placeholder="Name">
                            @error('name')
                            <div class="col-4"> <span class="text-danger ">{{ $message }}</span></div>
                           @enderror
                        </div>

                        <input type="hidden" name="item_category_id" id="item_category_id"  >
                            <div class="form-group mb-4 row">

                                <label  class="col-2">{{ __('key.proposalType') }}</label>
                                <select name="item_category_id" id="proposalType_selection" class="col-8 select2-show-search select2 form-control">
                                    <option selected disabled> Please choose ob_end_clean</option>
                                    @foreach ($categories as $category)
                                   
                                   <option value="{{ $category->id }}"
                                   {{ $category->id === $row->category->id ? "selected" : '' }}>{{$category->name}}</option>
                                   @endforeach
                                </select>
                                @error('item_category_id')
                                <div class="col-4"> <span class="text-danger ">{{ $message }}</span></div>
                               @enderror

                            </div>
                        <div class="form-group mb-4 float-right  ">

                            <button class="btn btn-success" type="submit" >{{ __('key.save') }}</button>
                            <a href="{{ route('sub-category.index') }}" class="btn btn-danger" type="submit" >{{ __('key.cancel') }}</a>
                        </div>

                    </div>

                </form>

            </div>

    </div>


    </div>


   @endsection
   @section('script')
   <script>
    $(document).ready(function(){
   
        // $('.select2-show-search').select2({
        //     minimumResultsForSearch: '',
        //     width: '66.7%'
        // });

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#proposalType_selection').val(selectedVehicleType).trigger("change");
        $("#proposalType_selection").on('select2:select', function (e) {

            let {value,name} = e.target;

            console.log(value);
            $('input[name="proposal_type_id"]').val(value);

        });

    })
</script>
   @endsection

resources/views/sub_category/index.blade.php
@extends('layouts.frontEnd')
@section('content')
    <!-- END SIDEBAR-->


    <div class="row">
        <div class="col-lg-12">
            <div class="card rounded border-0 my-5">
                <div class="card-body">
                    <div class="row dt-table-header">
                        <div class="px-4 d-flex align-items-center">
                            <h4 class="">{{ __('key.subcategoryList') }}</h4>
                        </div>
                        @include('layouts.msg_layouts')
                        <div class="col-12 d-flex justify-content-end">
                            <a href="{{ route('sub-category.create') }}"
                               class="btn btn-sm btn-primary mr-3 rounded ">
                                <i class="bi bi-plus-square"></i>&nbsp;<span>{{__('key.addNew')}}</span>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        
                        <table
                            class="table table-bordered table table-head-primary mb-4"
                            id="subCategoryDataTable" aria-describedby="heading">
                            <thead>

                            <tr>
                                <th>{{ __('key.name') }}</th>
                                <th>{{ __('key.categoryType') }}</th>
                                <th>{{ __('key.action') }}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- END QUICK SIDEBAR-->
@endsection
@section('script')
    <script type="text/javascript" src="{{ asset('js/dashboard/sub_category.js') }}">
    </script>
@endsection